backend:
  name: github
  repo: anton-v-svetlov/anton-v-svetlov.github.io
  branch: master

media_folder: "images/upload"   
  
options: 
  - Кухня
  - Изделия из массива дерева
  - Шкафы купe

collections: 
  - name: "massiv" 
    label: "Изделия из массива дерева"
    folder: "content/massiv"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография1", name: "photo1", widget: "image"}

  - name: "kuhni" 
    label: "Кухни"
    folder: "content/kuhni"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография1", name: "photo1", widget: "image"}
	  
  - name: "shkaf_kupe" 
    label: "Шкафы купе"
    folder: "content/shkaf_kupe"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография1", name: "photo1", widget: "image"}