backend:
  name: github
  repo: anton-v-svetlov/anton-v-svetlov.github.io
  branch: master

collections: 
  - name: "massiv" 
    label: "Изделия из массива дерева"
    folder: "сontent/massiv"
    media_folder: "images/gallery/massiv" 
    create: true
    fields:
      - {label: "Название", name: "title", widget: "string", tagname: "h1"}
      - {label: "Описание", name: "body", widget: "markdown"}
      - {label: "Фотография", name: "photo", widget: "image"}

  - name: "kuhni" 
    label: "Кухни"
    folder: "сontent/kuhni"
    media_folder: "images/gallery/kuhni" 
    create: true
    fields:
      - {label: "Название", name: "title", widget: "string", tagname: "h1"}
      - {label: "Описание", name: "body", widget: "markdown"}
      - {label: "Фотография", name: "photo", widget: "image"}	  