backend:
  name: github
  repo: anton-v-svetlov/anton-v-svetlov.github.io
  branch: master

media_folder: "images/upload"   
  
collections: 
  - name: "massiv" 
    label: "Изделия из массива дерева"
    folder: "сontent/massiv"

    create: true
    fields:
      - {label: "Название", name: "title", widget: "string", tagname: "h1"}
      - {label: "Описание", name: "body", widget: "markdown"}
      - {label: "Фотография", name: "photo", widget: "image"}

  - name: "kuhni" 
    label: "Кухни"
    folder: "сontent/kuhni"
    create: true
    fields:
      - {label: "Название", name: "title", widget: "string", tagname: "h1"}
      - {label: "Описание", name: "body", widget: "markdown"}
      - {label: "Фотография", name: "photo", widget: "image"}	  