backend:
  name: github
  repo: anton-v-svetlov/anton-v-svetlov.github.io
  branch: master

media_folder: "images/upload"   
  
options: 
  - Кухня
  - Изделия из массива дерева
  - Шкафы купе
  
collections: 
  - name: "massiv" 
    label: "Изделия из массива дерева"
    folder: "content/massiv"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография1", name: "photo1", widget: "image"}
      - {label: "Фотография2", name: "photo2", widget: "image", required: false}	
      - {label: "Фотография3", name: "photo3", widget: "image", required: false}		  
      - {label: "Фотография4", name: "photo4", widget: "image", required: false}		  
      - {label: "Фотография5", name: "photo5", widget: "image", required: false}	  
      - {label: "Фотография6", name: "photo6", widget: "image", required: false}	  

  - name: "kuhni" 
    label: "Кухни"
    folder: "content/kuhni"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография1", name: "photo1", widget: "image"}
      - {label: "Фотография2", name: "photo2", widget: "image", required: false}	
      - {label: "Фотография3", name: "photo3", widget: "image", required: false}		  
      - {label: "Фотография4", name: "photo4", widget: "image", required: false}		  
      - {label: "Фотография5", name: "photo5", widget: "image", required: false}	 
      - {label: "Фотография6", name: "photo6", widget: "image", required: false}	        
	  
  - name: "shkaf_kupe" 
    label: "Шкафы купе"
    folder: "content/shkaf_kupe"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография1", name: "photo1", widget: "image"}
      - {label: "Фотография2", name: "photo2", widget: "image", required: false}	
      - {label: "Фотография3", name: "photo3", widget: "image", required: false}		  
      - {label: "Фотография4", name: "photo4", widget: "image", required: false}		  
      - {label: "Фотография5", name: "photo5", widget: "image", required: false}	
      - {label: "Фотография6", name: "photo6", widget: "image", required: false}	        