backend:
  name: github
  repo: anton-v-svetlov/anton-v-svetlov.github.io
  branch: master

media_folder: "images/products/upload"   

collections: 
  - name: "products" 
    label: "Изделия"
    folder: "content/products"
    create: true
    fields:
      - {select: "Категория", name: "category", widget: "select",  options: ["kuhni", "massiv", "shkaf_kupe","detskaya", "stol"]}
      - {select: "Категория2", name: "category2", widget: "select",  options: ["kuhni", "massiv", "shkaf_kupe","detskaya", "stol"]}
      - {select: "Категория3", name: "category3", widget: "select",  options: ["kuhni", "massiv", "shkaf_kupe","detskaya", "stol"]}	  
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Главная Фотография", name: "photo1", widget: "image"}
      - {label: "Фотография2", name: "photo2", widget: "image", required: false}	  
      - {label: "Фотография3", name: "photo3", widget: "image", required: false}	  
      - {label: "Фотография4", name: "photo4", widget: "image", required: false}  
      - {label: "Фотография5", name: "photo5", widget: "image", required: false}
      - {label: "Модель(эскиз, чертеж, 3D, интерьер)", name: "model1", widget: "image", required: false}
      - {label: "Модель2", name: "model2", widget: "image", required: false}
      - {label: "Модель3", name: "model3", widget: "image", required: false}
      - {label: "Модель4", name: "model4", widget: "image", required: false}
      - {label: "Модель5", name: "model5", widget: "image", required: false}
      - {label: "Модель6", name: "model6", widget: "image", required: false}
 
  - name: "services" 
    label: "Сервисы"
    folder: "content/services"
    create: true
    fields:
      - {label: "Название latinicei", name: "title", widget: "string", tagname: "h1"}
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Фотография примера", name: "photo1", widget: "image"}
      - {label: "Иконка/пиктограмма", name: "model1", widget: "image", required: false}
	  
  - name: "persons" 
    label: "Люди"
    folder: "content/persons"
    create: true
    fields:
      - {label: "Имя latinicei", name: "title", widget: "string", tagname: "h1"}
      - {select: "Должность", name: "category", widget: "select",  options: ["founder", "partner", "owner","relative"]}	  
      - {label: "Короткое описание", name: "description", widget: "string"}
      - {label: "Длинное описание", name: "body", widget: "text", required: false}
      - {label: "Имя", name: "firstName", widget: "string"}
      - {label: "Отчество", name: "midName", widget: "string"}
      - {label: "Фамилия", name: "lastName", widget: "string"}	  
      - {label: "Ссылка", name: "link", widget: "string"}		  
      - {label: "Фотография 1", name: "photo1", widget: "image"}
      - {label: "Фотография 2", name: "photo1", widget: "image"}	  
      - {label: "Фотография 3", name: "photo1", widget: "image"}	        
